name: ML_pipeline
on : [push]

jobs :
  build :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r Exp2/requirements.txt

      - name: Run training script
        run: python Exp2/train.py